# fly.toml app configuration file generated for dc24-eu-wallet-issuer-workflow on 2024-07-23T08:49:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dc24-eu-wallet-issuer-workflow'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 8980
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  NGROK_URL = 'https://dc24-eu-wallet-issuer-workflow.fly.dev/callback'
