spring:
  main:
    web-application-type: reactive
  application:
    name: ansattporten-integration
  security:
    oauth2:
      client:
        registration:
          testclient:
            client-name: Logg inn med Ansattporten
            client-id: dc24_ansattporten_testclient
            client-secret: ${ANSATTPORTEN_CLIENT_SECRET:local}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/testclient"
            scope: openid, profile
            provider: ansattporten
        provider:
          ansattporten:
            issuer-uri: https://test.ansattporten.no
server:
  port: 8980
  address: 0.0.0.0

mattr:
  audience: ${MATTR_AUDIENCE:default_audience_value}
  tenant:
    url: ${MATTR_TENANT_URL:default_tenant_url}
  issuer: ${MATTR_ISSUER:default_issuer_value}
  client:
    secret: ${MATTR_CLIENT_SECRET:default_client_secret}
    id: ${MATTR_CLIENT_ID:default_client_id}
did:
  web: ${DID_WEB:default_did_web}
  web-extension: ${DID_WEB_EXTENSION:default_did_web_extension}
domain: ${DOMAIN:default_domain}

ngrok:
  url: ${NGROK_URL:local}

template:
  id: ${TEMPLATE_ID:upsi}


