spring:
  main:
    web-application-type: reactive
  application:
    name: ansattporten-integration
  security:
    oauth2:
      client:
        registration:
          testclient:
            client-name: Logg inn med Ansattporten
            client-id: dc24_ansattporten_testclient
            client-secret: ${ANSATTPORTEN_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/testclient"
            scope: openid, profile
            provider: ansattporten
        provider:
          ansattporten:
            issuer-uri: https://test.ansattporten.no
server:
  port: 8980

